# Generated by Django 2.1.4 on 2019-05-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Publish_name', models.CharField(max_length=50, verbose_name='发布项目')),
                ('script', models.CharField(max_length=500, verbose_name='脚本')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '发布脚本',
                'verbose_name_plural': '发布',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=50, verbose_name='名称')),
                ('hostname', models.CharField(max_length=50, verbose_name='IP')),
                ('username', models.CharField(max_length=50, verbose_name='账号')),
                ('passwd', models.CharField(max_length=50, verbose_name='密码')),
                ('port', models.CharField(max_length=50, verbose_name='端口')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '服务器用户',
                'db_table': 'Server',
            },
        ),
    ]
