# Generated by Django 2.1.4 on 2019-05-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_publish_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publish',
            name='create_time',
        ),
        migrations.AddField(
            model_name='publish',
            name='type',
            field=models.CharField(choices=[('CodePublish', '代码部署'), ('RunScrpit', '执行脚本')], default=1, max_length=50, verbose_name='发布类型'),
            preserve_default=False,
        ),
    ]
