# Generated by Django 2.1.4 on 2019-05-05 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20190505_1619'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Function',
        ),
    ]
