# Generated by Django 2.1.4 on 2019-05-09 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_delete_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='publish',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='demo.Server'),
            preserve_default=False,
        ),
    ]
