# Generated by Django 2.1.4 on 2019-05-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_publish_host'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
