# Generated by Django 2.1.4 on 2019-05-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_publish_param'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publish',
            name='type',
            field=models.CharField(choices=[('CodePublish', '代码部署'), ('RunScrpit', '执行脚本'), ('Monitor', '服务监控')], max_length=50, verbose_name='发布类型'),
        ),
    ]
